<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.addressbookpackageservices.AddressBookSystemTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2021-05-11T20:09:09" hostname="AVS-1997" time="0.255">
  <properties/>
  <testcase name="givenNewMobileNumberForEmployee_WhenUpdated_ShouldSyncWithDB()" classname="com.addressbookpackageservices.AddressBookSystemTest" time="0.255"/>
  <system-out><![CDATA[Driver loaded!
Connecting to database:jdbc:mysql://localhost:3306/addressbook_service?useSSL=false
Connection is successful!!!com.mysql.cj.jdbc.ConnectionImpl@323c50d5
Driver loaded!
Connecting to database:jdbc:mysql://localhost:3306/addressbook_service?useSSL=false
Connection is successful!!!com.mysql.cj.jdbc.ConnectionImpl@1dd13279
[Person{firstName='sai', lastName='nath', address='asrao nagar', city='hyderabad', state='telangana', zipCode='500040', email='sai@gmail.com', phoneNumber='708326675'}]
Driver loaded!
Connecting to database:jdbc:mysql://localhost:3306/addressbook_service?useSSL=false
Connection is successful!!!com.mysql.cj.jdbc.ConnectionImpl@2b2abc6a
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
